//
// Generated by sedonac 0.1.0
// 28-Apr-2019 11:03
//

#ifndef SEDONAC_SEDONA_PLATFORM_H
#define SEDONAC_SEDONA_PLATFORM_H

#define PLATFORM_ID "xungaoauto-0.1.0"
#define PLAT_BUILD_VERSION "0.1.0"

#endif
